[package]

name = "piston-ai_behavior"
version = "0.0.1"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>"
]
keywords = ["ai", "behavior", "piston", "game", "logic"]
description = "AI behavior tree"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/ai_behavior.git"
homepage = "https://github.com/pistondevelopers/ai_behavior"

[lib]

name = "ai_behavior"
path = "src/lib.rs"

[dependencies.pistoncore-event]

git = "https://github.com/PistonDevelopers/event"

[[test]]

name = "tests"
